<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We"
          crossorigin="anonymous">
    <title>Анализатор страниц</title>
</head>
<body>
<div class="col-lg-8 mx-auto p-4 py-md-5">
    <main>
        <nav>
            <ul>
                <li><a href="#home">Главная</a></li>
                <li><a href="#Url">Сайты</a></li>
            </ul>
        </nav>
        <h1 class="text-body-emphasis">Анализатор страниц</h1>
        <p>Javalin + jte</p>
    </main>
</div>
</body>
</html>
